# Command: sam local invoke LoadFunction --event events/event-pe.json

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for homologacion-zonas-virtuales

Resources:
  LoadFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./src/LoadFunction/
      Handler: LoadFunction::LoadFunction.Function::FunctionHandler
      Runtime: dotnetcore3.1
      Timeout: 600
      MemorySize: 256


